# Use official Nginx image
FROM nginx:latest

# Copy all files from current folder to nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80 (default for websites)
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
